server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          # **** /issuer1 registrations ****
          oidc-client:
            provider: spring-1
            client-id: client-1
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: oidc-client
          messaging-client-1-authorization-code:
            provider: spring-1
            client-id: client-1
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: message.read,message.write
            client-name: messaging-client-1-authorization-code
          messaging-client-1-client-credentials:
            provider: spring-1
            client-id: client-1
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: message.read,message.write
            client-name: messaging-client-1-client-credentials
          # **** /issuer2 registrations ****
          messaging-client-2-authorization-code:
            provider: spring-2
            client-id: client-2
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: message.read,message.write
            client-name: messaging-client-2-authorization-code
          messaging-client-2-client-credentials:
            provider: spring-2
            client-id: client-2
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: message.read,message.write
            client-name: messaging-client-2-client-credentials
        provider:
          spring-1:
            issuer-uri: http://localhost:9000/issuer1
          spring-2:
            issuer-uri: http://localhost:9000/issuer2

messages:
  base-uri: http://127.0.0.1:8090/messages
